function eRb(){}
function kRb(){}
function qRb(){}
function DRb(){}
function JRb(){}
function IRb(){}
function PRb(){}
function NRb(){}
function TRb(){}
function RRb(){}
function mRb(a){this.a=a}
function bBb(a,b){a._c(b)}
function ERb(a,b){iT(a.a);a$(a.a,b)}
function rRb(a,b){this.a=a;isb.call(this,b)}
function fRb(a,b,c){V8.call(this,a,b);this.a=c}
function VRb(){VRb=BYb;LRb=new PRb}
function WRb(){WRb=BYb;MRb=new TRb}
function SRb(a){if(!a.a){a.a=true;oi();Qc(li,YYb);ri();return true}return false}
function lRb(a,b){var c;c=new rRb(a,b.a);SW(c);LW(c);!c.j&&(c.j=eN(new SX(c)));XW(c)}
function FRb(){var a,b,c;this.b=(VRb(),MIb(),WRb(),b=new e$((c=new Rfb,new oJ(Ke(c.a))).a),a=new o3,n3(a,b),BU(a,b,(z$(),u$)),a.L.style[PZb]=w3b,this.a=b,ORb(LRb),SRb(MRb),a)}
function uBb(a){var b;!a.S&&(a.S=(b=new fRb((!a.a&&(a.a=new Hm),a.a),(!a.T&&(a.T=new FRb(new JRb)),a.T),(!a.R&&(a.R=new vRb),!a.c&&(a.c=RAb(new C7,new p7,cBb(),(!a.b&&(a.b=new z7),a.b))),a.c)),bBb(b,(!a.d&&(a.d=new x8),a.d)),b));return a.S}
function ORb(a){if(!a.a){a.a=true;qi((kq(),'.GDDO2QFFS{color:#222;font-family:arial, helvetica, sans-serif;font-size:16px;margin-top:6px;}.GDDO2QFMR{vertical-align:top;padding:25px;margin-left:65px;width:360px;border:1px solid #e5e5e5;text-align:left;background-color:whiteSmoke;}.GDDO2QFLR{color:#222;margin-bottom:6px;font-family:arial, helvetica, sans-serif;font-size:13px;font-weight:bold;}.GDDO2QFES{font-family:arial, helvetica, sans-serif;font-size:13px;color:#333;}.GDDO2QFOR{margin-top:3px;margin-bottom:26px;}.GDDO2QFAS{margin-top:-3px;float:left;}.GDDO2QFPR{font-family:arial, helvetica, sans-serif;font-size:16px;color:#333;margin-bottom:4px;}.GDDO2QFBS{font-family:arial, helvetica, sans-serif;font-size:13px;color:#333;}.GDDO2QFDS{color:#666;font-family:arial, helvetica, sans-serif;font-size:13px;}.GDDO2QFKR{color:#222;font-family:arial, helvetica, sans-serif;font-size:16px;margin-bottom:19px;}.GDDO2QFJR{color:#222;margin-bottom:6px;font-family:arial, helvetica, sans-serif;font-size:13px;font-weight:bold;}.GDDO2QFCS{padding-left:18px;padding-right:18px;}.GDDO2QFNR{padding:0 8px 0 8px;vertical-align:middle;}'));return true}return false}
_=YCb.prototype;_.eb=function aDb(){eab(this.b,uBb(this.a.a))};_=fRb.prototype=eRb.prototype=new L8;_.gC=function gRb(){return rF};_.ad=function hRb(){};_.cd=function iRb(){iT(ss(ss(this.f,178),179).a);c7(this.a,new XNb(ieb((prb(),prb(),orb).c.a.f)),new mRb(this))};_.dd=function jRb(){Q8(this,new ucb((Xwb(),Wwb),this))};_.cM={34:1,78:1,79:1};_.a=null;_=mRb.prototype=kRb.prototype=new ob;_.gC=function nRb(){return oF};_.db=function oRb(a){Zl(this.a.d,new oAb(e5b,a))};_.ic=function pRb(a){lRb(this,ss(a,170))};_.a=null;_=rRb.prototype=qRb.prototype=new gsb;_.gC=function sRb(){return nF};_.Kd=function tRb(){var a;if(hsb(this)){Zl(this.a.a.d,new zAb);a=new iY("<object width='850' height='790'><param name='movie' value='flash/lector.swf?classId="+hsb(this).f+y3b+(prb(),prb(),orb).c.a.b+z3b+orb.c.a.c+jZb+orb.c.a.d+"&amp;photo=http://domain.com/photo.jpg&amp;context_path=el-prototype'><\/param><param name='allowFullScreen' value='true'><\/param><param name='allowscriptaccess' value='always'><\/param><param name='wmode' value='opaque'><\/param><param name='context_path' value='el-prototype'><\/param><embed src='flash/lector.swf?classId="+hsb(this).f+y3b+orb.c.a.b+z3b+orb.c.a.c+jZb+orb.c.a.d+"&amp;photo=http://domain.com/photo.jpg&amp;context_path=el-prototype' wmode='opaque' type='application/x-shockwave-flash' width='850' height='790' allowscriptaccess='always' allowfullscreen='true'><\/embed><\/object>");ERb(ss(this.a.a.f,178),a)}CX(this)};_.cM={29:1,34:1,53:1,62:1,63:1,65:1,69:1,71:1};_.a=null;_=FRb.prototype=DRb.prototype=new i9;_.pc=function GRb(){return this.b};_.gC=function HRb(){return vF};_.cM={178:1,179:1};_.a=null;_.b=null;_=JRb.prototype=IRb.prototype=new ob;_.gC=function KRb(){return uF};var LRb=null,MRb=null;_=PRb.prototype=NRb.prototype=new ob;_.gC=function QRb(){return sF};_.a=false;_=TRb.prototype=RRb.prototype=new ob;_.gC=function URb(){return tF};_.a=false;var rF=udb(k3b,'TeacherVideoRoomPresenter'),vF=udb(k3b,'TeacherVideoRoomView'),oF=udb(k3b,'TeacherVideoRoomPresenter$1'),nF=udb(k3b,'TeacherVideoRoomPresenter$1$1'),uF=udb(k3b,'TeacherVideoRoomView_BinderImpl'),sF=udb(k3b,'TeacherVideoRoomView_BinderImpl_GenBundle_default_InlineClientBundleGenerator$1'),tF=udb(k3b,'TeacherVideoRoomView_BinderImpl_GenBundle_default_InlineClientBundleGenerator$2');WYb(qd)(7);