function GQb(){}
function MQb(){}
function SQb(){}
function dRb(){}
function jRb(){}
function iRb(){}
function pRb(){}
function nRb(){}
function tRb(){}
function rRb(){}
function OQb(a){this.b=a}
function DAb(a,b){a._c(b)}
function eRb(a,b){SS(a.b);KZ(a.b,b)}
function TQb(a,b){this.b=a;Krb.call(this,b)}
function HQb(a,b,c){v8.call(this,a,b);this.b=c}
function vRb(){vRb=bYb;lRb=new pRb}
function wRb(){wRb=bYb;mRb=new tRb}
function sRb(a){if(!a.b){a.b=true;ki();Qc(hi,zYb);ni();return true}return false}
function NQb(a,b){var c;c=new TQb(a,b.b);AW(c);tW(c);!c.k&&(c.k=XM(new AX(c)));FW(c)}
function fRb(){var a,b,c;this.c=(vRb(),mIb(),wRb(),b=new OZ((c=new rfb,new eJ(c.b.b)).b),a=new U2,T2(a,b),jU(a,b,(h$(),c$)),a.M.style[tZb]=W2b,this.b=b,oRb(lRb),sRb(mRb),a)}
function WAb(a){var b;!a.T&&(a.T=(b=new HQb((!a.b&&(a.b=new Em),a.b),(!a.U&&(a.U=new fRb(new jRb)),a.U),(!a.S&&(a.S=new XQb),!a.d&&(a.d=rAb(new c7,new R6,EAb(),(!a.c&&(a.c=new _6),a.c))),a.d)),DAb(b,(!a.e&&(a.e=new Z7),a.e)),b));return a.T}
function oRb(a){if(!a.b){a.b=true;mi((hq(),'.GDDO2QFFS{color:#222;font-family:arial, helvetica, sans-serif;font-size:16px;margin-top:6px;}.GDDO2QFMR{vertical-align:top;padding:25px;margin-left:65px;width:360px;border:1px solid #e5e5e5;text-align:left;background-color:whiteSmoke;}.GDDO2QFLR{color:#222;margin-bottom:6px;font-family:arial, helvetica, sans-serif;font-size:13px;font-weight:bold;}.GDDO2QFES{font-family:arial, helvetica, sans-serif;font-size:13px;color:#333;}.GDDO2QFOR{margin-top:3px;margin-bottom:26px;}.GDDO2QFAS{margin-top:-3px;float:left;}.GDDO2QFPR{font-family:arial, helvetica, sans-serif;font-size:16px;color:#333;margin-bottom:4px;}.GDDO2QFBS{font-family:arial, helvetica, sans-serif;font-size:13px;color:#333;}.GDDO2QFDS{color:#666;font-family:arial, helvetica, sans-serif;font-size:13px;}.GDDO2QFKR{color:#222;font-family:arial, helvetica, sans-serif;font-size:16px;margin-bottom:19px;}.GDDO2QFJR{color:#222;margin-bottom:6px;font-family:arial, helvetica, sans-serif;font-size:13px;font-weight:bold;}.GDDO2QFCS{padding-left:18px;padding-right:18px;}.GDDO2QFNR{padding:0 8px 0 8px;vertical-align:middle;}'));return true}return false}
_=yCb.prototype;_.fb=function CCb(){G9(this.c,WAb(this.b.b))};_=HQb.prototype=GQb.prototype=new l8;_.gC=function IQb(){return nF};_.ad=function JQb(){};_.cd=function KQb(){SS(ps(ps(this.g,178),179).b);E6(this.b,new xNb(Kdb((Rqb(),Rqb(),Qqb).d.b.g)),new OQb(this))};_.dd=function LQb(){q8(this,new Wbb((xwb(),wwb),this))};_.cM={34:1,78:1,79:1};_.b=null;_=OQb.prototype=MQb.prototype=new ob;_.gC=function PQb(){return kF};_.eb=function QQb(a){Wl(this.b.e,new Qzb(E4b,a))};_.ic=function RQb(a){NQb(this,ps(a,170))};_.b=null;_=TQb.prototype=SQb.prototype=new Irb;_.gC=function UQb(){return jF};_.Kd=function VQb(){var a;if(Jrb(this)){Wl(this.b.b.e,new _zb);a=new SX("<object width='850' height='790'><param name='movie' value='flash/lector.swf?classId="+Jrb(this).g+Y2b+(Rqb(),Rqb(),Qqb).d.b.c+Z2b+Qqb.d.b.d+KYb+Qqb.d.b.e+"&amp;photo=http://domain.com/photo.jpg&amp;context_path=el-prototype'><\/param><param name='allowFullScreen' value='true'><\/param><param name='allowscriptaccess' value='always'><\/param><param name='wmode' value='opaque'><\/param><param name='context_path' value='el-prototype'><\/param><embed src='flash/lector.swf?classId="+Jrb(this).g+Y2b+Qqb.d.b.c+Z2b+Qqb.d.b.d+KYb+Qqb.d.b.e+"&amp;photo=http://domain.com/photo.jpg&amp;context_path=el-prototype' wmode='opaque' type='application/x-shockwave-flash' width='850' height='790' allowscriptaccess='always' allowfullscreen='true'><\/embed><\/object>");eRb(ps(this.b.b.g,178),a)}kX(this)};_.cM={29:1,34:1,53:1,62:1,63:1,65:1,69:1,71:1};_.b=null;_=fRb.prototype=dRb.prototype=new K8;_.pc=function gRb(){return this.c};_.gC=function hRb(){return rF};_.cM={178:1,179:1};_.b=null;_.c=null;_=jRb.prototype=iRb.prototype=new ob;_.gC=function kRb(){return qF};var lRb=null,mRb=null;_=pRb.prototype=nRb.prototype=new ob;_.gC=function qRb(){return oF};_.b=false;_=tRb.prototype=rRb.prototype=new ob;_.gC=function uRb(){return pF};_.b=false;var nF=Wcb(K2b,'TeacherVideoRoomPresenter'),rF=Wcb(K2b,'TeacherVideoRoomView'),kF=Wcb(K2b,'TeacherVideoRoomPresenter$1'),jF=Wcb(K2b,'TeacherVideoRoomPresenter$1$1'),qF=Wcb(K2b,'TeacherVideoRoomView_BinderImpl'),oF=Wcb(K2b,'TeacherVideoRoomView_BinderImpl_GenBundle_default_InlineClientBundleGenerator$1'),pF=Wcb(K2b,'TeacherVideoRoomView_BinderImpl_GenBundle_default_InlineClientBundleGenerator$2');wYb(qd)(7);